# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7300d721cdc08557b68154999f8a30b4c638e216adf6fae4782726e333d11de59a9f884c5526b50204ad95a126fb8ea3c2d1bb6df213e36fa960c17625be554e

test:
  secret_key_base: 15b5d4b5f8c8b71df3c95f0da3d444c535466e0ca4a89bad21c598048c54193dc0e6292b6125d529b046f143c1bb35b3ec741fbe2840e0b85c37595af916ed3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
